project:
  type: book
book:
  title: "Title of the Master's Thesis"
  author: "Student Name"
  subtitle: "A dissertation submitted for the partial fulfilment of BS-MS dual degree in Science"
  description: "A dissertation submitted for the partial fulfilment of BS-MS dual degree in Science"
  downloads:
    - pdf
  language: en-IN
  type: thesis
  genre: master
  date: 2023/05/02
  date-title: "May 2023"
  date-format: long
  cover-image: ./images/HighResolutionLogo.jpg
  chapters:
    - index.qmd
    - intro.qmd
    - chapter1.qmd # Add more chapters here
    - references.qmd
  appendices:
    - appendix1.qmd # Add more appendices here

bibliography: references.bib

filters:
  - abstract-section

format:
  html:
    theme:
      light: yeti
    code-fold: false
    code-tools: true
    anchor-sections: true
    link-external-icon: true
    smooth-scroll: true
    csl: aip.csl
    link-citations: true
    code-block-bg: "#fcf6ef"
    code-block-border-left: "#04a5e5"
    highlight-style: atom-one
    number_sections: true
  pdf:
    regno: MS19xxx
    documentclass: scrbook
    fontsize: 12pt
    papersize: a4paper
    #monofont: JuliaMono # Uncomment if using Julia, install JuliaMono
    header-includes: "\\usepackage[list=true]{subcaption}"
    geometry:
      - a4paper
      - left=1.25in
      - right=1in
      - top=1in
      - bottom=1in
    linkcolor: blue
    toc: false
    csl: aip.csl
    link-citations: true
    supervisor: "Project Guide"
    TC1: "Thesis Committee1" # Local guide
    TC2: "Thesis Committee2"
    TC3: "Thesis Committee3"
    template-partials:
      - title.tex
      - before-body.tex
      - toc.tex
    code-block-bg: "#fcf6ef"
    code-block-border-left: "#04a5e5"
    highlight-style: atom-one
# Remove if you are not using code
execute:
  cache: true
  freeze: auto
  daemon: 1800
jupyter: python3
